PollPlus/Models/BannerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace PollPlus.Models
{
    public class BannerViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Campo obrigatório.")]
        public string Url { get; set; }
        public int EmpresaId { get; set; }

        public HttpPostedFileBase file { get; set; }
        public string fileName { get; set; }

        [Required(ErrorMessage ="Campo obbrigatório.")]
        public DateTime DataValidade { get; set; }

        public List<int> Empresas { get; set; }

        public List<int> Categorias { get; set; }
    }
}

PollPlus/Controllers/BannerController.cs
using PollPlus.Domain;
using PollPlus.Filter;
using PollPlus.Helpers;
using PollPlus.Models;
using PollPlus.Service.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PollPlus.Repositorio;

namespace PollPlus.Controllers
{
    [OnlyAuthorizedUser]
    public class BannerController : BaseController
    {
        readonly IBannerServiceWEB service;
        readonly IEmpresaServiceWEB serviceEmpresas;
        readonly IEnqueteServiceWEB serviceEnquete;

        private CategoriaBannerRepositorio catBanner = new CategoriaBannerRepositorio();
        private EmpresaBannerRepositorio empBanner = new EmpresaBannerRepositorio();

        public BannerController(IBannerServiceWEB srv, IEmpresaServiceWEB serviceEmpresa, IEnqueteServiceWEB srvEnquete)
        {
            this.service = srv;
            this.serviceEmpresas = serviceEmpresa;
            this.serviceEnquete = srvEnquete;
        }

        [HttpGet, OnlyAuthorizedUser]
        public async Task<ActionResult> NovoBanner()
        {
            var categorias = await this.serviceEnquete.RetornarCategoriasDisponniveis();
            ViewData.Add("CategoriasForSelectList", PreparaParaListaDeCategorias(categorias, null));

            var empresas = await this.serviceEmpresas.RetornarTodasEmpresas();
            ViewData.Add("EmpresasForSelectList", PreparaParaListaDeEmpresas(empresas, null));
            return View();
        }

        [HttpGet, OnlyAuthorizedUser]
        public async Task<ActionResult> EditarBanner(int bannerId)
        {
            var banner = await this.service.RetornarBannerPorId(bannerId);

            var categorias = await this.serviceEnquete.RetornarCategoriasDisponniveis();
            var b = banner.CategoriaBanner.Select(x => x.CategoriaId).ToList();
            ViewData.Add("CategoriasForSelectList", PreparaParaListaDeCategorias(categorias, b));

            var empresas = await this.serviceEmpresas.RetornarTodasEmpresas();
            var e = banner.EmpresaBanner.Select(x => x.EmpresaId).First();
            ViewData.Add("EmpresasForSelectList", PreparaParaListaDeEmpresas(empresas, e));

            return View(AutoMapper.Mapper.Map<BannerViewModel>(banner));
        }

        [HttpPost, OnlyAuthorizedUser]
        public async Task<ActionResult> EditarBanner(BannerViewModel model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if(await this.service.AtualizarBanner(AutoMapper.Mapper.Map<Banner>(model)))
                {
                    if (file.ContentLength > 0)
                        if (Util.SalvarImagem(file))
                            return RedirectToAction("ListarBanners");
                }
            }

            return View(model);
        }

        [HttpPost, OnlyAuthorizedUser]
        public async Task<ActionResult> NovoBanner(BannerViewModel model, HttpPostedFileBase file)
        {
            var categorias = await this.serviceEnquete.RetornarCategoriasDisponniveis();
            ViewData.Add("CategoriasForSelectList", PreparaParaListaDeCategorias(categorias, null));

            var empresas = await this.serviceEmpresas.RetornarTodasEmpresas();
            ViewData.Add("EmpresasForSelectList", PreparaParaListaDeEmpresas(empresas, null));
            if (!ModelState.IsValid)
                return View(model);

            if (UsuarioLogado.UsuarioAutenticado().Perfil == Domain.Enumeradores.EnumPerfil.AdministradorEmpresa)
                model.EmpresaId = (int)UsuarioLogado.UsuarioAutenticado().EmpresaId;

            model.fileName = file.FileName;
            var ban = await this.service.InserirRetornarBanner(AutoMapper.Mapper.Map<Banner>(model));
            if (ban != null)
            {
                if (model.Empresas != null)
                {
                    foreach (var item in model.Empresas)
                    {
                        await this.empBanner.InserirCB(new EmpresaBanner { EmpresaId = item, BannerId = ban.Id });
                    }
                }

                if (model.Categorias != null)
                {
                    foreach (var item in model.Categorias)
                    {
                        await this.catBanner.InserirCB(new CategoriaBanner { CategoriaId = item, BannerId = ban.Id });
                    }
                }

                if (file.ContentLength > 0)
                    if (Util.SalvarImagem(file))
                        return RedirectToAction("ListarBanners");
            }

            return View(model);
        }

        [HttpGet, OnlyAuthorizedUser]
        public async Task<ActionResult> ListarBanners(int? pagina)
        {
            var lista = await this.service.RetornarTodosBanners();

            return View(lista.OrderByDescending(x => x.DataCriacao).ToPagedList(pagina ?? 1, 10));
        }

        [OnlyAuthorizedUser, HttpGet]
        public async Task<ActionResult> DesativarBanner(int bannerId)
        {
            var banner = await this.service.RetornarBannerPorId(bannerId);
            banner.Status = Domain.Enumeradores.EnumStatusUsuario.Inativo;

            await this.service.AtualizarBanner(banner);

            return RedirectToAction("ListarBanners");
        }

        [OnlyAuthorizedUser, HttpGet]
        public async Task<ActionResult> AtivarBanner(int bannerId)
        {
            var banner = await this.service.RetornarBannerPorId(bannerId);
            banner.Status = Domain.Enumeradores.EnumStatusUsuario.Ativo;

            await this.service.AtualizarBanner(banner);

            return RedirectToAction("ListarBanners");
        }

        [NonAction]
        private static IEnumerable<SelectListItem> PreparaParaListaDeEmpresas(ICollection<Empresa> empresas, int? empresaSelecionada = null)
        {
            foreach (var empresa in empresas)
            {
                if (empresaSelecionada != null)
                {
                    yield return new SelectListItem
                    {
                        Text = empresa.Nome,
                        Value = empresa.Id.ToString(),
                        Selected = empresa.Id == empresaSelecionada
                    };
                }
                else
                {
                    yield return new SelectListItem
                    {
                        Text = empresa.Nome,
                        Value = empresa.Id.ToString()
                    };
                }
            }
        }

        [NonAction]
        private static IEnumerable<SelectListItem> PreparaParaListaDeCategorias(ICollection<Categoria> categorias, List<int> categoriaSelecionada = null)
        {
            foreach (var categoria in categorias)
            {
                if (categoriaSelecionada != null)
                {
                    yield return new SelectListItem
                    {
                        Text = categoria.Nome,
                        Value = categoria.Id.ToString(),
                        Selected = categoriaSelecionada.Contains((int)categoria.Id)
                    };
                }
                else
                {
                    yield return new SelectListItem
                    {
                        Text = categoria.Nome,
                        Value = categoria.Id.ToString()
                    };
                }
            }
        }
    }
}

PollPlus/Views/Banner/EditarBanner.cshtml
@model PollPlus.Models.BannerViewModel
    @using PollPlus.Helpers

@{
    ViewBag.Title = "Novo Banner";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="header">
    <h3>Cadastro de Banner</h3>
</div>

<div class="content tamanho-reduzido">

    @if (ViewBag.Mesagem != null)
    {
        @*@Html.RenderPartial("~/Views/Shared/_PartialExibirColecaoDeErros.cshtml", (List<string>)ViewBag.Mesagem);*@
    }

    @using (Html.BeginForm("EditarBanner", "Banner", FormMethod.Post, new { role = "form", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        <div class="form-group">
            @Html.LabelFor(x => x.Url, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Url, new { placeholder = "Insira a URL do banner", @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Url)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.DataValidade,"Valido até", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.DataValidade, new { placeholder = "Insira a data de validade deste banners", @class = "form-control datepicker" })
                @Html.ValidationMessageFor(x => x.DataValidade)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.file, "Imagem", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.file, new { type = "file" })
                @Html.ValidationMessageFor(x => x.file)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Categorias", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.Partial("_MultiSelectCategorias")
            </div>
        </div>

        if (UsuarioLogado.UsuarioAutenticado().Perfil == PollPlus.Domain.Enumeradores.EnumPerfil.AdministradorMaster)
        {
            <div class="form-group">
                @Html.Label("Empresa", new { @class = "col-sm-2 control-label" })
                <div class="col-sm-10">
                    @Html.Partial("_DropDownListForEmpresas")
                </div>
            </div>
        }

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-primary cancel" type="submit">Salvar</button>
                </div>
            </div>
    }

</div>

PollPlus/Views/Banner/ListarBanners.cshtml
@model PagedList.IPagedList<PollPlus.Domain.Banner>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Listar Banners";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="">

            @Html.ActionLink("Novo Banner", "NovoBanner", "Banner", null, new { @class = "btn btn-info" })

            <br />
            <div class="header">
                <h3>Listagem dos Banners Cadastrados</h3>
            </div>

            <div class="content">
                <div class="table-responsive">
                    <div role="grid" class="dataTables_wrapper form-inline" id="datatable_wrapper">
                        <table id="datatable" class="table table-bordered dataTable" aria-describedby="datatable_info">
                            <thead>
                                <tr role="row">
                                    <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 232px;" aria-label="">
                                        <strong>Url</strong>
                                    </th>
                                    <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 232px;" aria-label="">
                                        <strong>Empresa</strong>
                                    </th>
                                    <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 232px;" aria-label="">
                                        <strong>Data do Cadastro</strong>
                                    </th>
                                    <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 232px;" aria-label="">
                                        <strong>Data do Expiração</strong>
                                    </th>
                                    <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 232px;" aria-label="">
                                        <strong>Status</strong>
                                    </th>
                                    <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 120px;" aria-label="">
                                    </th>
                                </tr>
                            </thead>
                            <tbody role="alert" aria-live="polite" aria-relevant="all">

                                @foreach (var _banner in Model.OrderByDescending(x => x.DataCriacao))
                                {
                                    <tr class="gradeA odd">
                                        <td class=" ">@_banner.Url</td>
                                        <td class="">@(_banner.EmpresaBanner.FirstOrDefault() == null ? "Sem Empresa" : _banner.EmpresaBanner.First().Empresa.Nome)</td>
                                        <td class=" ">@_banner.DataCriacao.ToShortDateString()</td>
                                        <td class=" ">@_banner.DataValidade.ToShortDateString()</td>
                                        <td class=" ">@_banner.Status</td>
                                        <td class="center ">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default btn-xs">Ações</button>
                                                <button type="button" class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown">
                                                    <span class="caret"></span>
                                                    <span class="sr-only">Toggle Dropdown</span>
                                                </button>
                                                <ul class="dropdown-menu" role="menu">
                                                    <li><a href="@Url.Action("DesativarBanner", "Banner", new { bannerId = _banner.Id })">Desativar</a></li>
                                                    <li><a href="@Url.Action("AtivarBanner", "Banner", new { bannerId = _banner.Id })">Ativar</a></li>
                                                    <li><a href="@Url.Action("EditarBanner", "Banner", new { bannerId = _banner.Id })">Alterar</a></li>
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            @Html.PagedListPager(Model, page => Url.Action("ListarBanners", "Banner", new { pagina = page }),
            new PagedListRenderOptions
            {
                DisplayLinkToLastPage = PagedListDisplayMode.IfNeeded,
                DisplayLinkToPreviousPage = PagedListDisplayMode.IfNeeded,
                Display = PagedListDisplayMode.IfNeeded,
                LinkToNextPageFormat = "Próximo",
                LinkToPreviousPageFormat = "Anterior"
            })
        </div>
    </div>
</div>

PollPlus/Views/Banner/NovoBanner.cshtml
@model PollPlus.Models.BannerViewModel
@using PollPlus.Helpers

@{
    ViewBag.Title = "Novo Banner";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="header">
    <h3>Cadastro de Banner</h3>
</div>

<div class="content tamanho-reduzido">

    @if (ViewBag.Mesagem != null)
    {
        @*@Html.RenderPartial("~/Views/Shared/_PartialExibirColecaoDeErros.cshtml", (List<string>)ViewBag.Mesagem);*@
    }

    @using (Html.BeginForm("NovoBanner", "Banner", FormMethod.Post, new { role = "form", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        <div class="form-group">
            @Html.LabelFor(x => x.Url, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Url, new { placeholder = "Insira a URL do banner", @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Url)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.DataValidade, "Valido até", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.DataValidade, new { placeholder = "Insira a data de validade deste banners", @class = "form-control datepicker" })
                @Html.ValidationMessageFor(x => x.DataValidade)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.file, "Imagem", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.file, new { type = "file" })
                @Html.ValidationMessageFor(x => x.file)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Categorias", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.Partial("_MultiSelectCategorias")
            </div>
        </div>

        if (UsuarioLogado.UsuarioAutenticado().Perfil == PollPlus.Domain.Enumeradores.EnumPerfil.AdministradorMaster)
        {
            <div class="form-group">
                @Html.Label("Empresa", new { @class = "col-sm-2 control-label" })
                <div class="col-sm-10">
                    @Html.Partial("_DropDownListForEmpresas")
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-primary cancel" type="submit">Salvar</button>
            </div>
        </div>
    }

</div>

@section Scripts{

    <script>

        $(function () {



            $('#Url').focusout(function () {


                var tt = $('#Url').val();

                if ((tt.search(/www./g) != -1 && tt.search(/https:\/\//g) == -1) ||
                    (tt.search(/WWW./g) != -1 && tt.search(/HTTPS:\/\//g) == -1)) {
                    $('#Url').val(tt.replace(/www./g, 'http://'));
                } else if ((tt.search(/https:\/\//) != -1 && tt.search(/www./g) != -1) ||
                    (tt.search(/HTTPS:\/\//) != -1 && (tt.search(/WWW./g) != -1))) {
                    $('#Url').val(tt.replace(/https:\/\//g, 'http://'));
                    $('#Url').val(tt.replace(/www./g, ''));
                } else if (tt.search(/https:\/\//) != -1) {
                    $('#Url').val(tt.replace(/https:\/\//g, 'http://'));
                }
            });

        })


    </script>

}

PollPlus/Views/Banner/_DropDownlistForEmpresas.cshtml
@{var empresas = (IEnumerable<SelectListItem>)ViewData["EmpresasForSelectList"]; }

<select id="example3" multiple="multiple" name="Empresas" style="display: none;">
    @foreach (var cat in empresas)
    {
        <option value="@cat.Value" selected="@cat.Selected">@cat.Text</option>
    }
</select>

PollPlus/Views/Banner/_MultiSelectCategorias.cshtml
@{var categorias = (IEnumerable<SelectListItem>)ViewData["CategoriasForSelectList"]; }
<select id="example2" multiple="multiple" name="Categorias" style="display: none;">
    @foreach (var cat in categorias)
    {
        <option value="@cat.Value" selected="@cat.Selected">@cat.Text</option>
    }
</select>