PollPlus/Controllers/MapaController.cs
using Geocoding;
using Geocoding.Google;
using Newtonsoft.Json;
using PollPlus.Domain;
using PollPlus.Filter;
using PollPlus.Models;
using PollPlus.Repositorio;
using System;
using System.Collections.Generic;
using System.Data;
using System.Device.Location;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PollPlus.Controllers
{
    [OnlyAuthorizedUser]
    public class MapaController : BaseController
    {
        private GeolocalizacaoRepositorio geoRepo = new GeolocalizacaoRepositorio();

        private UsuarioRepositorio user = new UsuarioRepositorio();

        [HttpGet, OnlyAuthorizedUser]
        public async Task<ActionResult> Mapa()
        {
            var localizacoes = await geoRepo.RetornarTodasGeolocalizacoes();
            var dados = MontaIndicadoresNoMapaSemRadar(localizacoes);

            return View(dados);
        }

        [HttpPost, OnlyAuthorizedUser]
        public async Task<ActionResult> Sonar(string Latitude, string Longitude, string Raio)
        {

            var localizacoes = await geoRepo.RetornarTodasGeolocalizacoes();
            var dados = MontaIndicadoresNoMapaComRadar(localizacoes);

            ViewData.Add("Lat", Convert.ToDouble(Latitude));
            ViewData.Add("Long", Convert.ToDouble(Longitude));
            ViewData.Add("Raio", Convert.ToInt32(Raio));

            return View(dados);
        }

        // GET: Mapa
        public async Task<ActionResult> Index()
        {
            var localizacoes = await geoRepo.RetornarTodasGeolocalizacoes();
            var dados = MontaIndicadoresNoMapaSemRadar(localizacoes).Take(2);

            return View(dados);
        }

        [NonAction]
        private string RetornaEndereco(double latitude, double longitude)
        {
            //IGeocoder geocoder = new GoogleGeocoder();

            //try
            //{
            //    return geocoder.ReverseGeocode(latitude, longitude).First().FormattedAddress;
            //}
            //catch (Exception ex)
            //{
            //    throw ex;
            //}

            try
            {
                var key = "AIzaSyAJXiJ8FatzUwzUKOfgv3Eh9qMTlPewBu0";
                string url = "https://maps.googleapis.com/maps/api/geocode/json?latlng={0},{1}&key={2}";
                url = string.Format(url, latitude.ToString().Replace(',', '.'), longitude.ToString().Replace(',', '.'), key);
                HttpClient client = new HttpClient();

                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var result = client.GetStringAsync(new Uri(url)).Result;
                var endereco = JsonConvert.DeserializeObject<RootObject>(result);

                return endereco != null && endereco.results != null && endereco.results.Any() ?
                    endereco.results.First().formatted_address :
                    "Endereço não resolvido pelo Google";
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [NonAction]
        private IEnumerable<MapViewModel> MontaIndicadoresNoMapaComRadar(ICollection<Geolocalizacao> posicoes)
        {
            var lista = new List<MapViewModel>();
            var group = posicoes.GroupBy(x => x.UsuarioId).Distinct();
            var tempo = DateTime.Now.AddDays(-180);

            foreach (var posicao in group)
            {
                foreach (var item in posicao.Where(x => x.DataCriacao >= tempo))
                {
                    yield return new MapViewModel
                    {
                        Latitude = item.Latitude,
                        Longitude = item.Longitude,
                        //Endereco = RetornaEndereco(posicao.Latitude, posicao.Longitude),
                        Nome = item.Usuario.Nome,
                        Icon = item.Usuario.Perfil == Domain.Enumeradores.EnumPerfil.AdministradorEmpresa ?
                    "IconMarkerOutrasEmpresas.png" : "IconMarkerMais.png"
                    };
                }
            }
        }

        [NonAction]
        private IEnumerable<MapViewModel> MontaIndicadoresNoMapaSemRadar(ICollection<Geolocalizacao> posicoes)
        {
            var lista = new List<MapViewModel>();

            foreach (var item in posicoes)
            {
                yield return new MapViewModel
                {
                    Latitude = item.Latitude,
                    Longitude = item.Longitude,
                    //Endereco = RetornaEndereco(posicao.Latitude, posicao.Longitude),
                    Nome = item.Usuario.Nome,
                    Icon = item.Usuario.Perfil == Domain.Enumeradores.EnumPerfil.AdministradorEmpresa ?
    "IconMarkerOutrasEmpresas.png" : item.Usuario.Perfil == Domain.Enumeradores.EnumPerfil.Vendedor ?
    "IconMarkerVendedorMais.png" : "IconMarkerMais.png"
                };
            }
        }

        private async Task<Usuario> RetornaDadosDoUsuario(int usuarioId)
        {
            return await this.user.RetornarUsuarioPorId(usuarioId);
        }

        [HttpGet, OnlyAuthorizedUser]
        public async Task<JsonResult> AtualizaContadorMapaPessoas(string Latitude, string Longitude, string Raio)
        {
            var localizacoes = await geoRepo.RetornarTodasGeolocalizacoes();

            var listaUsuario = new List<Usuario>();

            foreach (var geo in localizacoes)
            {
                if (CalcularDistancia(Convert.ToDouble(Latitude), Convert.ToDouble(Longitude), geo.Latitude, geo.Longitude, Convert.ToInt32(Raio)))
                {
                    if (!listaUsuario.Contains(geo.Usuario))
                        listaUsuario.Add(geo.Usuario);
                }
            }
            return Json(listaUsuario.Count, JsonRequestBehavior.AllowGet);
        }

        [NonAction]
        private bool CalcularDistancia(double latOrigem, double lonOrigem, double latUsuario, double lonUsuario, double alcance)
        {
            var localOrigem = new GeoCoordinate(latOrigem, lonOrigem);
            var localUsuario = new GeoCoordinate(latUsuario, lonUsuario);

            var distancia = localOrigem.GetDistanceTo(localUsuario);

            return distancia <= alcance;
        }
    }

    public class AddressComponent
    {
        public string long_name { get; set; }
        public string short_name { get; set; }
        public List<string> types { get; set; }
    }

    public class Northeast
    {
        public double lat { get; set; }
        public double lng { get; set; }
    }

    public class Southwest
    {
        public double lat { get; set; }
        public double lng { get; set; }
    }

    public class Bounds
    {
        public Northeast northeast { get; set; }
        public Southwest southwest { get; set; }
    }

    public class Location
    {
        public double lat { get; set; }
        public double lng { get; set; }
    }

    public class Northeast2
    {
        public double lat { get; set; }
        public double lng { get; set; }
    }

    public class Southwest2
    {
        public double lat { get; set; }
        public double lng { get; set; }
    }

    public class Viewport
    {
        public Northeast2 northeast { get; set; }
        public Southwest2 southwest { get; set; }
    }

    public class Geometry
    {
        public Bounds bounds { get; set; }
        public Location location { get; set; }
        public string location_type { get; set; }
        public Viewport viewport { get; set; }
    }

    public class Result
    {
        public List<AddressComponent> address_components { get; set; }
        public string formatted_address { get; set; }
        public Geometry geometry { get; set; }
        public string place_id { get; set; }
        public List<string> types { get; set; }
    }

    public class RootObject
    {
        public List<Result> results { get; set; }
        public string status { get; set; }
    }
}

PollPlus/Controllers/PushController.cs
using PollPlus.Domain;
using PollPlus.Filter;
using PollPlus.Helpers;
using PollPlus.Models;
using PollPlus.Repositorio;
using PollPlus.Service;
using System;
using System.Collections.Generic;
using System.Device.Location;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PollPlus.Controllers
{
    [OnlyAuthorizedUser]
    public class PushController : BaseController
    {
        private UsuarioRepositorio usuarioRepo = new UsuarioRepositorio();
        private GeolocalizacaoRepositorio geoRepositorio = new GeolocalizacaoRepositorio();
        private EmpresaRepositorio empresaRepositorio = new EmpresaRepositorio();

        [HttpGet, OnlyAuthorizedUser]
        public ActionResult NovoPush()
        {
            return View();
        }

        [HttpGet, OnlyAuthorizedUser]
        public ActionResult NovoPushPorArea()
        {
            return View();
        }

        [HttpGet, OnlyAuthorizedUser]
        public ActionResult NovoAgendamentoPorAcaoImportacao()
        {
            return View();
        }

        [HttpPost, OnlyAuthorizedUser]
        public async Task<ActionResult> NovoAgendamentoPorAcaoImportacao(HttpPostedFileBase file)
        {
            if (file.ContentLength <= 0)
                return View(0);

            try
            {
                var pushs = (ICollection<PushProgramado>)Util.ImportarCSV(EnumTipoImportacao.PushProgramado, file);

                foreach (var item in pushs)
                {
                    var usuario = await this.usuarioRepo.RetornarUsuarioPorEmail(item.UsuarioEmail);

                    if (usuario != null)
                    {
                        var _empresa = await this.empresaRepositorio.RetornarEmpresaPorId((int)UsuarioLogado.UsuarioAutenticado().EmpresaId);

                        if (_empresa.QtdePush > 0)
                        {
                            var lista = new List<KeyValuePair<string, DateTime>> { new KeyValuePair<string, DateTime>(usuario.PushWooshToken, item.DataEnvio) };
                            var result = this.EnvioPushWooshResult(lista, item.Mensagem);

                            if (result)
                            {
                                _empresa.QtdePush = _empresa.QtdePush - pushs.Count;
                                await this.empresaRepositorio.AtualizarEmpresa(_empresa);
                            }
                        }
                    }
                }

                return View(1);
            }
            catch (Exception ex)
            {
                return View(0);
            }
        }

        [HttpPost, OnlyAuthorizedUser]
        public async Task<ActionResult> NovoPush(NovaMensagemPushViewModel p_mensagem)
        {
            if (!ModelState.IsValid)
                return View(p_mensagem);

            var _empresa = await this.empresaRepositorio.RetornarEmpresaPorId((int)UsuarioLogado.UsuarioAutenticado().EmpresaId);

            if (_empresa.QtdePush > 0)
            {
                var _retornoPushWoosh = EnvioPushWooshResult(p_mensagem);

                if (_retornoPushWoosh)
                {
                    _empresa.QtdePush = _empresa.QtdePush - 1;
                    await this.empresaRepositorio.AtualizarEmpresa(_empresa);
                }
            }

            return View();
        }

        [HttpPost, OnlyAuthorizedUser]
        public async Task<ActionResult> NovoPushPorArea(NovaMensagemPushViewModel p_mensagem)
        {
            if (ModelState.IsValid)
            {
                var empresa = (int)UsuarioLogado.UsuarioAutenticado().EmpresaId;

                var geoCollection = await this.geoRepositorio.RetornarGeoPorUsuarioPorEmpresa(empresa);

                var geoValidas = new List<string>();
                var tempo = DateTime.Now.AddDays(-30);

                foreach (var geo in geoCollection.Distinct().Where(x => x.DataCriacao >= tempo))
                {
                    //if (distance(p_mensagem.Latitude, p_mensagem.Longitude, geo.Latitude, geo.Longitude, 'K', p_mensagem.Area))
                    //{
                    //    geoValidas.Add(geo.Usuario.PushWooshToken);
                    //}

                    if (CalcularDistancia(Convert.ToDouble(p_mensagem.Latitude), Convert.ToDouble(p_mensagem.Longitude), geo.Latitude, geo.Longitude, Convert.ToInt32(p_mensagem.Area)))
                    {
                        if (!String.IsNullOrEmpty(geo.Usuario.PushWooshToken) && !geoValidas.Contains(geo.Usuario.PushWooshToken))
                            geoValidas.Add(geo.Usuario.PushWooshToken);
                    }
                }

                if (geoValidas.Any())
                {
                    var enviados = new List<UsuariosEnvioPushPorArea>();
                    var _empresa = await this.empresaRepositorio.RetornarEmpresaPorId((int)UsuarioLogado.UsuarioAutenticado().EmpresaId);

                    if (_empresa.QtdePush > 0)
                    //if (1 == 1)//TESTE
                    {
                        var _retornoPushWoosh = this.EnvioPushWooshResult(geoValidas, p_mensagem.Mensagem);

                        if (_retornoPushWoosh)
                        //if (1 == 1)//TESTE
                        {
                            foreach (var item in geoValidas)
                            {
                                var _usuario = await this.RetornaUsuarioPorPushWooshID(item);
                                enviados.Add(new UsuariosEnvioPushPorArea
                                {
                                    DataHoraEnvio = DateTime.Now,
                                    Mensagem = p_mensagem.Mensagem,
                                    Nome = _usuario.Nome,
                                    NomeEmpresa = UsuarioLogado.UsuarioAutenticado().Empresa.Nome,
                                    //EnderecoOrigem = this.RetornaEnderecoOrigem(Convert.ToDouble(p_mensagem.Latitude.Replace(',', '.'), Convert.ToDouble(p_mensagem.Longitude.Replace(',', '.'))))
                                });
                            }

                            ViewBag.UsuariosEnviados = enviados;

                            _empresa.QtdePush = _empresa.QtdePush - geoValidas.Count;
                            await this.empresaRepositorio.AtualizarEmpresa(_empresa);
                        }
                    }

                    ViewBag.Erro = "Envio Concluido.";
                    return View();
                }

                ViewBag.Erro = "Nenhum usuário dentro do raio inserido.";

                return View();

            }

            ViewBag.Erro = "Dados informados fora do formato esperado.";

            return View();
        }

        [NonAction]
        private async Task<Usuario> RetornaUsuarioPorPushWooshID(string pushWooshID)
        {
            return await this.usuarioRepo.RetornarUsuarioPorPushWooshID(pushWooshID);
        }

        [NonAction]
        public string RetornaEnderecoOrigem(double lat, double lon)
        {
            var resolver = new CivicAddressResolver();
            var coord = new GeoCoordinate(lat, lon);
            var address = resolver.ResolveAddress(coord);

            return address.AddressLine1;
        }

        [NonAction]
        private bool EnvioPushWooshResult(NovaMensagemPushViewModel p_mensagem)
        {
            var _retornoPushWoosh = new EnvioPush().EnviarPushNotification(p_mensagem.Mensagem);

            return _retornoPushWoosh;
        }

        [NonAction]
        private bool EnvioPushWooshResult(List<string> p_mensagens, string texto)
        {
            var _retornoPushWoosh = new EnvioPush().EnviarPushNotification(p_mensagens, texto);

            return _retornoPushWoosh;
        }

        [NonAction]
        private bool EnvioPushWooshResult(List<KeyValuePair<string, DateTime>> p_novoPush, string texto)
        {
            var _retornoPushWoosh = new EnvioPush().EnviarPushNotificationProgramado(p_novoPush, texto);

            return _retornoPushWoosh;
        }

        [NonAction]
        private bool distance(double lat1, double lon1, double lat2, double lon2, char unit, int raio)
        {
            double theta = lon1 - lon2;
            double dist = Math.Sin(deg2rad(lat1)) * Math.Sin(deg2rad(lat2)) + Math.Cos(deg2rad(lat1)) * Math.Cos(deg2rad(lat2)) * Math.Cos(deg2rad(theta));
            dist = Math.Acos(dist);
            dist = rad2deg(dist);
            dist = dist * 60 * 1.1515;
            if (unit == 'K')
            {
                dist = dist * 1.609344;
            }
            else if (unit == 'N')
            {
                dist = dist * 0.8684;
            }
            return (dist) <= (double)raio;
        }

        [NonAction]
        private bool CalcularDistancia(double latOrigem, double lonOrigem, double latUsuario, double lonUsuario, double alcance)
        {
            var localOrigem = new GeoCoordinate(latOrigem, lonOrigem);
            var localUsuario = new GeoCoordinate(latUsuario, lonUsuario);

            var distancia = localOrigem.GetDistanceTo(localUsuario);

            return distancia <= alcance;
        }

        [NonAction]
        private double deg2rad(double deg)
        {
            return (deg * Math.PI / 180.0);
        }

        [NonAction]
        private double rad2deg(double rad)
        {
            return (rad / Math.PI * 180.0);
        }
    }
}

PollPlus/Views/Menu/_MenuBanners.cshtml
@*<Banners>*@
<li class="parent">
    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Banners</span>
    </a>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Cadastrar Banner", "NovoBanner", "Banner")
        </li>
        <li>
            @Html.ActionLink("Listar Banners", "ListarBanners", "Banner")
        </li>
    </ul>
</li>
@*</Banners>*@

PollPlus/Views/Menu/_MenuCategoria.cshtml
@*<Categorias>*@
<li class="parent">
    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Categorias</span>
    </a>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Cadastrar Categoria", "NovaCategoria", "Categoria")
        </li>
        <li>
            @Html.ActionLink("Listar Categorias", "ListarCategorias", "Categoria")
        </li>
    </ul>
</li>
@*</Categorias>*@

PollPlus/Views/Menu/_MenuControleAcesso.cshtml
@*<Voucher>*@
<li class="parent">
    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Controle de Acesso</span>
    </a>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Novo acesso", "NovoControleAcesso", "ControleAcesso")
        </li>
        <li>
            @Html.ActionLink("Listar Acessos Liberados", "ListarControlesAcessos", "ControleAcesso")
        </li>
    </ul>
</li>
@*</Voucher>*@

PollPlus/Views/Menu/_MenuEmpresas.cshtml
@*<Empresas>*@
<li class="parent">
    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Empresas</span>
    </a>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Cadastrar Empresa", "NovaEmpresa", "Empresa")
        </li>
        <li>
            @Html.ActionLink("Listar Empresas", "ListarEmpresas", "Empresa")
        </li>
        @*<li>
            @Html.ActionLink("Cadastrar Filial", "NovaFilial", "Empresa")
        </li>*@
        @*<li>
            @Html.ActionLink("Listar Filiais", "ListarFiliais", "Empresa")
        </li>*@
    </ul>
</li>
@*</Empresas>*@

PollPlus/Views/Menu/_MenuEnquetes.cshtml
@*<Enquete>*@
<li class="parent">
    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Enquetes</span>
    </a>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Criar Enquete", "NovaEnquete", "Enquete")
        </li>
        <li>
            @Html.ActionLink("Listar Enquetes", "ListarEnquetes", "Enquete")
        </li>
        <li>
            @Html.ActionLink("Importar Black List", "ImportarBlackList", "Enquete")
        </li>
    </ul>
</li>
@*</Enquete>*@

PollPlus/Views/Menu/_MenuMapas.cshtml
@*<Mapas>*@
<li class="parent">
    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Mapas e Localição</span>
    </a>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Exibir Localizações", "Index", "Mapa")
        </li>
    </ul>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Radar de Localizações", "Mapa", "Mapa")
        </li>
    </ul>
</li>
@*</Mapas>*@

PollPlus/Views/Menu/_MenuMensagens.cshtml
@*<Mensagem>*@
<li class="parent">
    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Notícias</span>
    </a>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Criar Notícia", "NovaMensagem", "Mensagem")
        </li>
        @*<li>
            @Html.ActionLink("Criar Modelo de Mensagem", "NovoModeloMensagem", "Mensagem")
        </li>*@
        <li>
            @Html.ActionLink("Listar Notícias", "ListarMensagens", "Mensagem")
        </li>
    </ul>
</li>
@*</Mensagem>*@

PollPlus/Views/Menu/_MenuPush.cshtml
@*<Mapas>*@
<li class="parent">
    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Push</span>
    </a>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Enviar Push para base", "NovoPush", "Push")
        </li>
        <li>
            @Html.ActionLink("Enviar Push por Área", "NovoPushPorArea", "Push")
        </li>
        <li>
            @Html.ActionLink("Enviar Push Programado por Importação", "NovoAgendamentoPorAcaoImportacao", "Push")
        </li>
    </ul>
</li>
@*</Mapas>*@

PollPlus/Views/Menu/_MenuQuiz.cshtml
@*<Quiz>*@
<li class="parent">
    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Quiz</span>
    </a>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Criar Quiz", "NovoQuiz", "Quiz")
        </li>
        <li>
            @Html.ActionLink("Listar Quiz", "ListarQuiz", "Quiz")
        </li>
    </ul>
</li>
@*</Quiz>*@

PollPlus/Views/Menu/_MenuRelatorio.cshtml
@*<Vendas>*@
<li class="parent">
    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Relatórios</span>
    </a>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Usuários cadastrados", "RelUsuariosCadastrados", "Relatorio")
        </li>
        <li>
            @Html.ActionLink("Empresas cadastradas", "RelEmpresasCadastradas", "Relatorio")
        </li>
        <li>
            @Html.ActionLink("Enquetes cadastradas", "RelEnquetesCadastradas", "Relatorio")
        </li>
        <li>
            @Html.ActionLink("Exporta Respostas por Sexo", "RelEstatisticoPorSexo", "Relatorio")
        </li>
        <li>
            @Html.ActionLink("Exporta Respostas por Idade", "RelEstatisticoPorIdade", "Relatorio")
        </li>
        <li>
            @Html.ActionLink("Exporta Respostas por Município", "RelEstatisticoPorMunicipio", "Relatorio")
        </li>
    </ul>
</li>
@*</Vendas>*@

PollPlus/Views/Menu/_MenuUsuarios.cshtml
@*<Usuarios>*@
<li class="parent">
    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Usuários</span>
    </a>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Criar Usuário", "NovoUsuario", "Account")
        </li>
        <li>
            @Html.ActionLink("Listar Usuários", "ListarUsuarios", "Account")
        </li>
        <li>
            @Html.ActionLink("Importar Usuários", "ImportarEmail", "Account")
        </li>
        <li>
            @Html.ActionLink("Importar Dados para envio Promocional", "ImportarDadosConcessionaria", "Account")
        </li>
    </ul>
</li>
@*</Usuário>*@

PollPlus/Views/Menu/_MenuVouchers.cshtml
@*<Voucher>*@
<li class="parent">
    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Vouchers</span>
    </a>
    <ul class="sub-menu" style="display: none;">
        <li>
            @Html.ActionLink("Criar Voucher", "NovoVoucher", "Voucher")
        </li>
        <li>
            @Html.ActionLink("Listar Vouchers", "ListarVouchers", "Voucher")
        </li>
    </ul>
</li>
@*</Voucher>*@