PollPlus/Models/RelEmpresaViewModel.cs
using SimpleExcelExport;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PollPlus.Models
{
    public class RelEmpresaViewModel
    {
        [ExcelExport("Nome")]
        public string Nome { get; set; }

        [ExcelExport("Documento")]
        public string Documento { get; set; }

        [ExcelExport("Data de Criação")]
        public string DataCriacao { get; set; }

        [ExcelExport("Quantidade de Push")]
        public string QtdePush { get; set; }
    }
}

PollPlus/Models/RelEnquetesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SimpleExcelExport;

namespace PollPlus.Models
{
    public class RelEnquetesViewModel
    {
        [ExcelExport("ID")]
        public int Id { get; set; }

        [ExcelExport("Pergunta")]
        public string TextoPergunta { get; set; }

        [ExcelExport("Categoria")]
        public string Categoria { get; set; }

        [ExcelExport("Possui Voucher?")]
        public string TemVoucher { get; set; }

        [ExcelExport("Link do vídeo")]
        public string UrlVideo { get; set; }

        [ExcelExport("Arquivo da imagem")]
        public string Imagem { get; set; }

        [ExcelExport("Status")]
        public string Status { get; set; }

        [ExcelExport("Data de criação")]
        public string DataCriacao { get; set; }
    }
}

PollPlus/Models/RelUsuarios.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SimpleExcelExport;

namespace PollPlus.Models
{
    public class RelUsuariosViewModdel
    {
        [ExcelExport("Nome")]
        public string Nome { get; set; }

        [ExcelExport("Data de Nascimento")]
        public DateTime DataNascimento { get; set; }

        [ExcelExport("E-mail")]
        public string Email { get; set; }

        [ExcelExport("Telefone")]
        public string Telefone { get; set; }
    }
}

PollPlus/Models/RelUsuariosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SimpleExcelExport;

namespace PollPlus.Models
{
    public class RelUsuariosViewModel
    {
        [ExcelExport("Nome")]
        public string Nome { get; set; }

        [ExcelExport("Data de Nascimento")]
        public string DataNascimento { get; set; }

        [ExcelExport("E-mail")]
        public string Email { get; set; }

        [ExcelExport("Telefone")]
        public string Telefone { get; set; }

        [ExcelExport("Data de criação")]
        public string DataCriacao { get; set; }

        [ExcelExport("Município")]
        public string Municipio { get; set; }

        [ExcelExport("Sexo")]
        public string Sexo { get; set; }
    }
}

PollPlus/Controllers/RelatorioController.cs
using PollPlus.Domain;
using PollPlus.Helpers;
using PollPlus.Service.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PollPlus.Filter;
using PollPlus.Models;
using PollPlus.Domain.Enumeradores;

namespace PollPlus.Controllers
{
    [OnlyAuthorizedUser]
    public class RelatorioController : Controller
    {
        readonly IUsuarioServiceWEB srvUsuario;
        readonly IEmpresaServiceWEB srvEmpresa;
        readonly IEnqueteServiceWEB srvEnquete;
        readonly IRespostaServiceWEB srvResposta;
        readonly IPerguntaRespostaServiceWEB srvPerguntaResposta;

        private object Cache { get; set; }

        public RelatorioController(IUsuarioServiceWEB srvUsuario,
            IEmpresaServiceWEB srvEmpresa, IEnqueteServiceWEB srvEnquete, IPerguntaRespostaServiceWEB srvPerguntaService,
            IRespostaServiceWEB srvResposta)
        {
            this.srvUsuario = srvUsuario;
            this.srvEmpresa = srvEmpresa;
            this.srvEnquete = srvEnquete;
            this.srvPerguntaResposta = srvPerguntaService;
            this.srvResposta = srvResposta;
        }

        [NonAction]
        private static IEnumerable<SelectListItem> PreparaParaListaDeEmpresas(ICollection<Empresa> empresas, int? empresaSelecionada = null)
        {
            foreach (var empresa in empresas)
            {
                if (empresaSelecionada != null)
                {
                    yield return new SelectListItem
                    {
                        Text = empresa.Nome,
                        Value = empresa.Id.ToString(),
                        Selected = empresa.Id == empresaSelecionada
                    };
                }

                yield return new SelectListItem
                {
                    Text = empresa.Nome,
                    Value = empresa.Id.ToString()
                };
            }
        }

        [HttpGet]
        public async Task<ActionResult> RelUsuariosCadastrados()
        {
            var empresas = await this.srvEmpresa.RetornarTodasEmpresas();
            ViewData.Add("EmpresasForSelectList", PreparaParaListaDeEmpresas(empresas, null));

            if (UsuarioLogado.UsuarioAutenticado().Perfil == Domain.Enumeradores.EnumPerfil.AdministradorMaster)
            {
                var _usuarios = await this.srvUsuario.RetornarTodosUsuarios();
                var _toList = _usuarios.GroupBy(x => x.Email);

                var listaUsuarios = new List<Usuario>();

                foreach (var usuarios in _toList)
                {
                    foreach (var usuario in usuarios)
                    {
                        if (!listaUsuarios.Any(x => x.Email == usuario.Email))
                            listaUsuarios.Add(usuario);
                    }
                }

                this.Cache = listaUsuarios;

                return View("RelUsuarios", listaUsuarios.OrderByDescending(c => c.DataCriacao).ToPagedList(1, 10));
            }
            else
            {
                var _usuarios = await this.srvUsuario.RetornarTodosUsuarios();
                var _toList = _usuarios.Where(e => e.EmpresaId == UsuarioLogado.UsuarioAutenticado().EmpresaId).GroupBy(x => x.Email);

                var listaUsuarios = new List<Usuario>();

                foreach (var usuarios in _toList)
                {
                    foreach (var usuario in usuarios)
                    {
                        if (!listaUsuarios.Any(x => x.Email == usuario.Email))
                            listaUsuarios.Add(usuario);
                    }
                }

                this.Cache = listaUsuarios;

                return View("RelUsuarios", listaUsuarios.OrderByDescending(c => c.DataCriacao).ToPagedList(1, 10));
            }
        }

        [HttpGet]
        public async Task<ActionResult> ExportarUsuariosCadastrados()
        {
            if (UsuarioLogado.UsuarioAutenticado().Perfil == Domain.Enumeradores.EnumPerfil.AdministradorMaster)
            {
                var _usuarios = await this.srvUsuario.RetornarTodosUsuarios();
                var _toList = _usuarios.OrderBy(x => x.Nome).ToList();

                var listaUsuarios = new List<Usuario>();

                foreach (var usuarios in _toList)
                {
                    foreach (var usuario in _usuarios)
                    {
                        if (!listaUsuarios.Any(x => x.Email == usuario.Email))
                            listaUsuarios.Add(usuario);
                    }
                }


                var mapper = listaUsuarios.Select(x => new RelUsuariosViewModel
                {
                    Nome = String.IsNullOrEmpty(x.Nome) ? "Não Informado" : x.Nome,
                    Email = String.IsNullOrEmpty(x.Email) ? "Não Informado" : x.Email,
                    Telefone = String.IsNullOrEmpty(x.Telefone) ? "Não Informado" : x.Telefone,
                    DataCriacao = x.DataCriacao.ToShortDateString(),
                    DataNascimento = x.DataNascimento == null ? "Não Informado" : x.DataNascimento.Value.ToShortDateString(),
                    Municipio = String.IsNullOrEmpty(x.Municipio) ? "Não Informado" : x.Municipio,
                    Sexo = x.Sexo == null ? "Não Informado" : x.Sexo.GetDescription()
                });

                var _arqExcelBytes = new SimpleExcelExport.ExportToExcel().ListToExcel<RelUsuariosViewModel>(mapper.ToList());
                return File(_arqExcelBytes, "application/ms-excel", string.Format("Relatorio_Cadastro_Usuarios_{0}.xls", DateTime.Now.ToShortDateString()));
            }
            else
            {
                var _usuarios = await this.srvUsuario.RetornarTodosUsuarios();
                var _toList = _usuarios.Where(e => e.EmpresaId == UsuarioLogado.UsuarioAutenticado().EmpresaId).OrderBy(x => x.Nome).ToList();

                var listaUsuarios = new List<Usuario>();

                foreach (var usuarios in _toList)
                {
                    foreach (var usuario in _usuarios)
                    {
                        if (!listaUsuarios.Any(x => x.Email == usuario.Email))
                            listaUsuarios.Add(usuario);
                    }
                }

                var mapper = listaUsuarios.Select(x => new RelUsuariosViewModel
                {
                    Nome = String.IsNullOrEmpty(x.Nome) ? "Não Informado" : x.Nome,
                    Email = String.IsNullOrEmpty(x.Email) ? "Não Informado" : x.Email,
                    Telefone = String.IsNullOrEmpty(x.Telefone) ? "Não Informado" : x.Telefone,
                    DataCriacao = x.DataCriacao.ToShortDateString(),
                    DataNascimento = x.DataNascimento == null ? "Não Informado" : x.DataNascimento.Value.ToShortDateString(),
                });

                var _arqExcelBytes = new SimpleExcelExport.ExportToExcel().ListToExcel<RelUsuariosViewModel>(mapper.ToList());
                return File(_arqExcelBytes, "application/ms-excel", string.Format("Relatorio_Cadastro_Usuarios_{0}.xls", DateTime.Now.ToShortDateString()));
            }
        }

        [HttpGet]
        public async Task<ActionResult> RelUsuariosCadastradosPaginado(int? empresaId, int? page)
        {
            var empresas = await this.srvEmpresa.RetornarTodasEmpresas();
            ViewData.Add("EmpresasForSelectList", PreparaParaListaDeEmpresas(empresas, empresaId));

            if (empresaId != null)
            {
                var _usuarios = await this.srvUsuario.RetornarTodosUsuarios();
                var _filtroUsuarios = _usuarios.Where(e => e.EmpresaId == UsuarioLogado.UsuarioAutenticado().EmpresaId).OrderBy(x => x.Nome).ToList();
                this.Cache = _filtroUsuarios;

                return View("RelUsuarios", _filtroUsuarios.ToPagedList(page ?? 1, 10));
            }
            else
            {
                var _usuarios = await this.srvUsuario.RetornarTodosUsuarios();
                var _filtroUsuarios = _usuarios.OrderBy(x => x.Nome).ToList();
                this.Cache = _filtroUsuarios;

                return View("RelUsuarios", _filtroUsuarios.ToPagedList(page ?? 1, 10));
            }
        }

        [HttpGet]
        public async Task<ActionResult> RelEmpresasCadastradas(int? page)
        {
            var _empresas = await this.srvEmpresa.RetornarTodasEmpresas();
            var _toList = _empresas.ToList();

            return View("RelEmpresas", _toList.ToPagedList(page ?? 1, 10));
        }

        [HttpGet]
        public async Task<ActionResult> ExportarEmpresasCadastrados()
        {
            var _empresas = await this.srvEmpresa.RetornarTodasEmpresas();
            var _toList = _empresas.ToList();
            var mapper = _toList.Select(x => new RelEmpresaViewModel
            {
                Nome = x.Nome,
                Documento = x.Documento.Numero.ToString(),
                DataCriacao = x.DataCriacao.ToShortDateString(),
                QtdePush = x.QtdePush.ToString()
            });

            var _arqExcelBytes = new SimpleExcelExport.ExportToExcel().ListToExcel<RelEmpresaViewModel>(mapper.ToList());
            return File(_arqExcelBytes, "application/ms-excel", string.Format("Relatorio_Cadastro_Empresa_{0}.xls", DateTime.Now.ToShortDateString()));
        }

        [HttpGet]
        public async Task<ActionResult> RelEnquetesCadastradas()
        {
            var empresas = await this.srvEmpresa.RetornarTodasEmpresas();
            ViewData.Add("EmpresasForSelectList", PreparaParaListaDeEmpresas(empresas, null));

            if (UsuarioLogado.UsuarioAutenticado().Perfil == Domain.Enumeradores.EnumPerfil.AdministradorEmpresa)
            {
                var enquetes = await this.srvEnquete.RetornarTodasEnquetes();

PollPlus/Views/Relatorio/RelEmpresas.cshtml
@model PagedList.IPagedList<PollPlus.Domain.Empresa>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Relatório Gerencial - Empresas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .ui-autocomplete-loading {
        background: white url("../../Content/images/loader-autocomplete.gif") right center no-repeat;
    }
</style>

<div class="content tamanho-reduzido">

    <div class="header">
        <h3>Relatório Gerencial - Empresas Cadatradas</h3>
    </div>

    @Html.Partial("_GridRelatorioEmpresas", Model)

    <br />

    @Html.PagedListPager(Model, page => Url.Action("RelEmpresasCadastradas", "Relatorio", new { page = page }),
                new PagedListRenderOptions
                {
                    DisplayLinkToLastPage = PagedList.Mvc.PagedListDisplayMode.IfNeeded,
                    DisplayLinkToPreviousPage = PagedListDisplayMode.IfNeeded,
                    Display = PagedListDisplayMode.IfNeeded,
                    LinkToNextPageFormat = "Próximo",
                    LinkToPreviousPageFormat = "Anterior"
                })

    <br />
    <br />

    @using (Html.BeginForm("ExportarEmpresasCadastrados", "Relatorio", FormMethod.Get, new { role = "form", @class = "form-horizontal" }))
    {
        if (Model != null)
        {
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-primary" type="submit">Exportar</button><br />
                </div>
            </div>
        }
    }
</div>

@section Scripts{
    <script type="text/javascript">

    </script>
}

PollPlus/Views/Relatorio/RelEnquetes.cshtml
@model PagedList.IPagedList<PollPlus.Domain.Enquete>
@using PollPlus.Helpers;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Relatório Gerencial - Enquetes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .ui-autocomplete-loading {
        background: white url("../../Content/images/loader-autocomplete.gif") right center no-repeat;
    }
</style>

<div class="content tamanho-reduzido">

    <div class="header">
        <h3>Relatório Gerencial - Enquetes Cadatradas</h3>
    </div>

    @using (Html.BeginForm("RelEnquetesCadastradas", "Relatorio", FormMethod.Get, new { role = "form", @class = "form-horizontal" }))
    {
        if (UsuarioLogado.UsuarioAutenticado().Perfil == PollPlus.Domain.Enumeradores.EnumPerfil.AdministradorMaster)
        {
            <div class="form-group">
                @Html.Label("Empresa", new { @class = "col-sm-2 control-label" })
                <div class="col-sm-10">
                    @Html.Partial("_DropDownListForEmpresas")
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-primary cancel" type="submit">Gerar</button><br />
            </div>
        </div>
        <br />

        <div>
            <div class="content" id="listaVinculos">
                <div class="header">
                    <h3>Associações</h3>
                </div>
                <br />
                @{
                    Html.RenderPartial("_GridRelatorioEnquetes", Model);
                }
            </div>
        </div>

        <br />
                    }

    <br />

    @Html.PagedListPager(Model, page => Url.Action("RelEnquetesCadastradasPaginada", "Relatorio", new { page = page }),
                new PagedListRenderOptions
                {
                    DisplayLinkToLastPage = PagedList.Mvc.PagedListDisplayMode.IfNeeded,
                    DisplayLinkToPreviousPage = PagedListDisplayMode.IfNeeded,
                    Display = PagedListDisplayMode.IfNeeded,
                    LinkToNextPageFormat = "Próximo",
                    LinkToPreviousPageFormat = "Anterior"
                })
    <br />

    @using (Html.BeginForm("ExportarEnquetesCadastradas", "Relatorio", FormMethod.Get, new { role = "form", @class = "form-horizontal" }))
    {
        if (Model != null)
        {
            @*<div class="form-group">
                    @Html.Label("Enquete", new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-10">
                        @Html.Partial("_DropDownListForEnquete")
                    </div>
                </div>*@

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-primary" type="submit">Exportar Enquetes</button><br />
                </div>
            </div>
        }
    }
    <br />
    <br />
    @using (Html.BeginForm("ExportarRespostasEnquete", "Relatorio", FormMethod.Get, new { role = "form", @class = "form-horizontal" }))
    {
        if (Model != null)
        {
            <div class="form-group">
                @Html.Label("Enquete", new { @class = "col-sm-2 control-label" })
                <div class="col-sm-10">
                    @Html.Partial("_DropDownListForEnquete")
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-primary" type="submit">Exportar Respostas da Enquete Selecionada</button><br />
                </div>
            </div>
        }
    }
</div>

@section Scripts{
    <script type="text/javascript">
        $(function () {

        });
    </script>

    <script type="text/javascript">
        //Add dataTable Functions
        var functions = $('<div class="btn-group"><button class="btn btn-default btn-xs" type="button">Actions</button><button data-toggle="dropdown" class="btn btn-xs btn-primary dropdown-toggle" type="button"><span class="caret"></span><span class="sr-only">Toggle Dropdown</span></button><ul role="menu" class="dropdown-menu"><li><a href="#">Edit</a></li><li><a href="#">Copy</a></li><li><a href="#">Details</a></li><li class="divider"></li><li><a href="#">Remove</a></li></ul></div>');
        $("#datatable tbody tr td:last-child").each(function () {
            $(this).html("");
            functions.clone().appendTo(this);
        });

        $(document).ready(function () {
            //initialize the javascript
            //Basic Instance
            $("#datatable").dataTable();

            /* Formating function for row details */
            function fnFormatDetails(oTable, nTr) {
                var aData;
                var perguntaID = $(nTr).attr('id');
                var parametro = JSON.stringify({ perguntaId: perguntaID });
                var sOut = "";

                $.ajax({
                    url: "@Url.Action("GetRespostasComPercentual", "Relatorio")",
                    type: "POST",
                    data: parametro,
                    dataType: "json",
                    async: false,
                    contentType: 'application/json; charset=utf-8',
                    success: function (data, textStatus, jqXHR) {
                        if (data.length > 0) {

                            for (var i = 0; i < data.length; i++) {
                                sOut += '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
                                sOut += '<tr><td style="width: 1%;">Resposta:</td><td>' + data[i].TextoResposta + '</td></tr>';
                                sOut += '<tr><td style="width: 1%;">Percentual de votos:</td><td>' + data[i].Percentual + '</td></tr>';
                                sOut += '</table>';
                            }
                        }
                        else {
                            sOut += '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
                            sOut += '<tr><td>Houve um erro ao processar a informação. Recarregue a página</td></tr>';
                            sOut += '</table>';
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        sOut += '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
                        sOut += '<tr><td>Houve um erro ao processar a informação. Recarregue a página</td></tr>';
                        sOut += '</table>';
                        Console.log = jqXHR;
                    }
                });

                return sOut;
            }

            /*
             * Insert a 'details' column to the table
             */
            var nCloneTh = document.createElement('th');
            var nCloneTd = document.createElement('td');
            nCloneTd.innerHTML = '<img class="toggle-details" src="/Content/Theme/images/plus.png" />';
            nCloneTd.className = "center";

            $('#datatable2 thead tr').each(function () {
                this.insertBefore(nCloneTh, this.childNodes[0]);
            });

            $('#datatable2 tbody tr').each(function () {
                this.insertBefore(nCloneTd.cloneNode(true), this.childNodes[0]);
            });

            /*
             * Initialise DataTables, with no sorting on the 'details' column
             */
            var oTable = $('#datatable2').dataTable({
                "aoColumnDefs": [
                    { "bSortable": false, "aTargets": [0] }
                ],
                "aaSorting": [[1, 'asc']]
            });

            /* Add event listener for opening and closing details
             * Note that the indicator for showing which row is open is not controlled by DataTables,
             * rather it is done here
             */
            $('#datatable2').delegate('tbody td img', 'click', function () {
                var nTr = $(this).parents('tr')[0];
                if (oTable.fnIsOpen(nTr)) {
                    /* This row is already open - close it */
                    this.src = "/Content/Theme/images/plus.png";
                    oTable.fnClose(nTr);
                }
                else {
                    /* Open this row */
                    this.src = "/Content/Theme/images/minus.png";
                    oTable.fnOpen(nTr, fnFormatDetails(oTable, nTr), 'details');
                }
            });

            //$('.dataTables_filter input').addClass('form-control').attr('placeholder', 'Search');
            //$('.dataTables_length select').addClass('form-control');

            $('#datatable2').prev().remove();
            $('#datatable2').next().remove();

        });
    </script>
}

PollPlus/Views/Relatorio/RelEstatisticoPorIdade.cshtml
@model PagedList.IPagedList<PollPlus.Domain.Enquete>
@using PollPlus.Helpers;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Relatório Gerencial - Enquetes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .ui-autocomplete-loading {
        background: white url("../../Content/images/loader-autocomplete.gif") right center no-repeat;
    }
</style>

<div class="content tamanho-reduzido">

    <div class="header">
        <h3>Relatório Gerencial de Enquete - Respostas  por Idade</h3>
    </div>

    @using (Html.BeginForm("ExportaRelEnquetesCadastradasPorIdade", "Relatorio", FormMethod.Get, new { role = "form", @class = "form-horizontal" }))
    {
        <div class="form-group">
            @Html.Label("Enquete", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.Partial("_DropDownListForEnquete")
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-primary cancel" type="submit">Gerar</button><br />
            </div>
        </div>
    }
</div>

@section Scripts{
    <script type="text/javascript">
        $(function () {

        });
    </script>
}

PollPlus/Views/Relatorio/RelEstatisticoPorMunicipio.cshtml
@model PagedList.IPagedList<PollPlus.Domain.Enquete>
@using PollPlus.Helpers;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Relatório Gerencial - Enquetes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .ui-autocomplete-loading {
        background: white url("../../Content/images/loader-autocomplete.gif") right center no-repeat;
    }
</style>

<div class="content tamanho-reduzido">

    <div class="header">
        <h3>Relatório Gerencial de Enquete - Respostas  por Municipio</h3>
    </div>

    @using (Html.BeginForm("ExportaRelEnquetesCadastradasPorMunicipio", "Relatorio", FormMethod.Get, new { role = "form", @class = "form-horizontal" }))
    {

        <div class="form-group">
            @Html.Label("Enquete", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.Partial("_DropDownListForEnquete")
            </div>
        </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-primary cancel" type="submit">Gerar</button><br />
                </div>
            </div>
    }
</div>
@section Scripts{
    <script type="text/javascript">
        $(function () {

        });
    </script>
}

PollPlus/Views/Relatorio/RelEstatisticoPorSexo.cshtml
@model PagedList.IPagedList<PollPlus.Domain.Enquete>
@using PollPlus.Helpers;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Relatório Gerencial - Enquetes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .ui-autocomplete-loading {
        background: white url("../../Content/images/loader-autocomplete.gif") right center no-repeat;
    }
</style>

<div class="content tamanho-reduzido">

    <div class="header">
        <h3>Relatório Gerencial de Enquete - Respostas  por Sexo</h3>
    </div>

    @using (Html.BeginForm("ExportaRelEnquetesCadastradasPorSexo", "Relatorio", FormMethod.Get, new { role = "form", @class = "form-horizontal" }))
    {

        <div class="form-group">
            @Html.Label("Enquete", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.Partial("_DropDownListForEnquete")
            </div>
        </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-primary cancel" type="submit">Gerar</button><br />
                </div>
            </div>
    }
</div>

@section Scripts{
    <script type="text/javascript">
        $(function () {

        });
    </script>
}

PollPlus/Views/Relatorio/_DropDownlistForEnquete.cshtml
@{var enquetes = (IEnumerable<SelectListItem>)ViewData["EnqueteForSelectList"]; }

@if (enquetes.Any())
{
    @Html.DropDownList("EnqueteId", enquetes, "Selecione uma enquete");
}
else
{
    <p>Erro ao carregar lista de Enquetes.</p>
}

PollPlus/Views/Relatorio/_GridRelatorio.cshtml
@model PagedList.IPagedList<PollPlus.Domain.Usuario>
@using GridMvc.Html;
@using PollPlus.Helpers;

<div>

    <div class="header">
        <h3>Informações</h3>
    </div>

    <div class="content" id="DadosRelatorio">
        <div id="tabelaListaColaboradores" class="table-responsive">
            <div role="grid" class="dataTables_wrapper form-inline" id="datatable_wrapper">
                @if (Model != null && Model.Any())
                {
                    @Html.Grid(Model).Columns(col =>
               {
                   col.Add(b => b.Nome);
                   col.Add(b => b.Email);
                   col.Add(b => b.Telefone);
                   col.Add(b => b.DataNascimento).Titled("Data de Nascimento").Format("{0:dd/MM/yyy}");
                   col.Add(b => b.DataCriacao).Titled("Data do cadastro").Format("{0:dd/MM/yyy}");
                   col.Add(b => b.Municipio).Titled("Município");
                   col.Add(b => b.Sexo).Titled("Sexo");
               });
                }
                else
                {
                    <p>Nenhum registro encontrado.</p>
                }
            </div>
        </div>
    </div>
</div>