PollPlus/Models/VoucherViewModel.cs
using PollPlus.Domain.Enumeradores;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PollPlus.Models
{
    public class VoucherViewModel
    {
        public int Id { get; set; }
        public int QtdeVoucherParaEmitir { get; set; }
        public EnumStatusVoucher Status { get; set; }
        public string Descricao { get; set; }
        public DateTime DataValidade { get; set; }
        public int EmpresaId { get; set; }
        public int EnqueteId { get; set; }
        public string ImagemEmail { get; set; }

        public List<string> NroVoucher { get; set; }
    }
}

PollPlus/Controllers/VoucherController.cs
using PagedList;
using PollPlus.Domain;
using PollPlus.Filter;
using PollPlus.Helpers;
using PollPlus.Models;
using PollPlus.Service.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PollPlus.Controllers
{
    [OnlyAuthorizedUser]
    public class VoucherController : BaseController
    {
        readonly IVoucherServiceWEB _service;

        readonly IEmpresaServiceWEB serviceEmpresas;

        readonly IEnqueteServiceWEB serviceEnquete;

        public VoucherController(IVoucherServiceWEB service, IEmpresaServiceWEB serviceEmpresas, IEnqueteServiceWEB serviceEnquete)
        {
            this._service = service;
            this.serviceEmpresas = serviceEmpresas;
            this.serviceEnquete = serviceEnquete;
        }

        [OnlyAuthorizedUser, HttpGet]
        public async Task<ActionResult> NovoVoucher()
        {
            if (UsuarioLogado.UsuarioAutenticado().Perfil == Domain.Enumeradores.EnumPerfil.AdministradorEmpresa)
            {
                var enquetes = await this.serviceEnquete.RetornarTodasEnquetes();
                var filtro = enquetes.Where(e => e.Id == UsuarioLogado.UsuarioAutenticado().EmpresaId).ToList();
                ViewData.Add("EnqueteForSelectList", PreparaParaListaDeEnquetes(filtro, null));
            }
            else
            {
                var enquetes = await this.serviceEnquete.RetornarTodasEnquetes();
                ViewData.Add("EnqueteForSelectList", PreparaParaListaDeEnquetes(enquetes.Where(x => x.PerguntaId != null).ToList(), null));
            }
            return View();
        }

        [OnlyAuthorizedUser, HttpPost]
        public async Task<ActionResult> NovoVoucher(VoucherViewModel model, string NroVoucher, HttpPostedFileBase file)
        {
            if (UsuarioLogado.UsuarioAutenticado().Perfil == Domain.Enumeradores.EnumPerfil.AdministradorEmpresa)
            {
                var enquetes = await this.serviceEnquete.RetornarTodasEnquetes();
                var filtro = enquetes.Where(e => e.Id == UsuarioLogado.UsuarioAutenticado().EmpresaId &&
                e.Tipo == Domain.Enumeradores.EnumTipoEnquete.Publica).ToList();
                ViewData.Add("EnqueteForSelectList", PreparaParaListaDeEnquetes(filtro, null));
            }
            else
            {
                var enquetes = (await this.serviceEnquete.RetornarTodasEnquetes()).Where(e => e.Tipo == Domain.Enumeradores.EnumTipoEnquete.Publica).ToList();
                ViewData.Add("EnqueteForSelectList", PreparaParaListaDeEnquetes(enquetes, null));
            }

            if (!ModelState.IsValid)
                return View(model);

            if (file.ContentLength > 0)
            {
                model.ImagemEmail = file.FileName;

                Util.SalvarImagem(file);
            }

            foreach (var item in NroVoucher.Split(",".ToCharArray(), StringSplitOptions.RemoveEmptyEntries))
            {
                var v = new Voucher { DataValidade = model.DataValidade, Identificador = item, Status = Domain.Enumeradores.EnumStatusVoucher.Disponivel, Usado = false, ImagemEmail = file.ContentLength > 0 ? file.FileName : string.Empty };
                var voucher = await this._service.InserirRetornarVoucher(v);
                if (voucher != null)
                    await this._service.AssociaVoucherEnquete(model.EnqueteId, voucher.Id);
            }

            var enquente = await this.serviceEnquete.RetornarEnquetePorId(model.EnqueteId);
            enquente.TemVoucher = true;
            await this.serviceEnquete.AtualizarEnquete(enquente);

            return RedirectToAction("ListarVouchers");
        }

        [OnlyAuthorizedUser, HttpGet]
        public async Task<ActionResult> EditarVoucher(int voucherId)
        {
            var voucher = await this._service.RetornarVoucherPorId(voucherId);

            return View(AutoMapper.Mapper.Map<VoucherViewModel>(voucher));
        }

        [OnlyAuthorizedUser, HttpPost]
        public async Task<ActionResult> EditarVoucher(VoucherViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (await this._service.AtualizarVoucher(AutoMapper.Mapper.Map<Voucher>(model)))
                return RedirectToAction("ListarVouchers");

            return View(model);
        }

        [OnlyAuthorizedUser, HttpGet]
        public async Task<ActionResult> ListarVouchers(int? pagina)
        {
            var lista = await this._service.RetornarTodosVouchers();
            var listaEnquete = new List<Enquete>();

            foreach (var item in lista)
            {
                foreach (var e in item.EnqueteVoucher)
                {
                    listaEnquete.Add(await this.serviceEnquete.RetornarEnquetePorId(e.EnqueteId));
                }
            }

            foreach (var item in lista.SelectMany(x => x.EnqueteVoucher))
            {
                item.Enquete = listaEnquete.First(x => x.Id == item.EnqueteId);
            }

            if (listaEnquete.Any())
                ViewBag.Enquetes = listaEnquete;

            return View(lista.OrderByDescending(x => x.DataCriacao).ToPagedList(pagina ?? 1, 10));
        }

        [OnlyAuthorizedUser, HttpGet]
        public async Task<ActionResult> MarcarComoUtilizado(int voucherId)
        {
            var voucher = await this._service.RetornarVoucherPorId(voucherId);
            voucher.Usado = true;
            voucher.Status = Domain.Enumeradores.EnumStatusVoucher.Indisponivel;

            await this._service.AtualizarVoucher(voucher);

            return RedirectToAction("ListarVouchers");
        }

        [NonAction]
        private static IEnumerable<SelectListItem> PreparaParaListaDeEnquetes(ICollection<Enquete> enquetes, int? enqueteSelecionada = null)
        {
            foreach (var enquete in enquetes)
            {
                if (enqueteSelecionada != null)
                {
                    yield return new SelectListItem
                    {
                        Text = enquete.Pergunta.TextoPergunta,
                        Value = enquete.Id.ToString(),
                        Selected = enquete.Id == enqueteSelecionada
                    };
                }
                else
                {
                    yield return new SelectListItem
                    {
                        Text = enquete.Pergunta.TextoPergunta,
                        Value = enquete.Id.ToString()
                    };
                }
            }
        }
    }
}

PollPlus/Views/Voucher/ListarVouchers.cshtml
@model PagedList.IPagedList<PollPlus.Domain.Voucher>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Listar Vouchers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Model != null && Model.Any())
{
    <div class="row">
        <div class="col-md-12">
            <div class="">

                @Html.ActionLink("Novo Voucher", "NovoVoucher", "Voucher", null, new { @class = "btn btn-info" })

                <br />
                <div class="header">
                    <h3>Listagem dos Vouchers Cadastrados</h3>
                </div>

                <div class="content">
                    <div class="table-responsive">
                        <div role="grid" class="dataTables_wrapper form-inline" id="datatable_wrapper">
                            <table id="datatable" class="table table-bordered dataTable" aria-describedby="datatable_info">
                                <thead>
                                    <tr role="row">
                                        <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 232px;" aria-label="">
                                            <strong>Número</strong>
                                        </th>
                                        <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 232px;" aria-label="">
                                            <strong>Status</strong>
                                        </th>
                                        <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 232px;" aria-label="">
                                            <strong>Data da Criação</strong>
                                        </th>
                                        <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 232px;" aria-label="">
                                            <strong>Data da Validade</strong>
                                        </th>
                                        <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 232px;" aria-label="">
                                            <strong>Enquete</strong>
                                        </th>
                                        <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 232px;" aria-label="">
                                            <strong>Empresa</strong>
                                        </th>
                                        <th role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" style="width: 120px;" aria-label="">
                                        </th>
                                    </tr>
                                </thead>
                                <tbody role="alert" aria-live="polite" aria-relevant="all">

                                    @foreach (var _voucher in Model)
                                    {
                                        <tr class="gradeA odd">
                                            <td class=" ">@_voucher.Identificador</td>
                                            <td style="color:red;font-weight:bold">@_voucher.Status</td>
                                            <td class=" ">@_voucher.DataCriacao.ToShortDateString()</td>
                                            <td class=" ">@_voucher.DataValidade</td>
                                            <td class=" ">@(_voucher.EnqueteVoucher.First().Enquete.Pergunta.TextoPergunta)</td>
                                            @if (_voucher.EnqueteVoucher.FirstOrDefault() != null &&
                            _voucher.EnqueteVoucher.FirstOrDefault().Enquete != null &&
                            _voucher.EnqueteVoucher.FirstOrDefault().Enquete.Empresa != null)
                                            {
                                                <td class=" ">@(_voucher.EnqueteVoucher.First().Enquete.Empresa.Nome)</td>
                                            }
                                            else
                                            {
                                                <td class=" ">Sem Empresa associada</td>
                                            }
                                            <td class="center ">
                                                @if (!_voucher.Usado)
                                                {
                                                    <div class="btn-group">
                                                        <button type="button" class="btn btn-default btn-xs">Ações</button>
                                                        <button type="button" class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown">
                                                            <span class="caret"></span>
                                                            <span class="sr-only">Toggle Dropdown</span>
                                                        </button>
                                                        <ul class="dropdown-menu" role="menu">
                                                            <li><a href="javascript: if(confirm('Deseja marcar como utilizado?')) {window.location.href='@Url.Action("MarcarComoUtilizado", "Voucher", new { voucherId = _voucher.Id })';}">Utilizado</a></li>
                                                        </ul>
                                                    </div>
                                                }
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                @Html.PagedListPager(Model, page => Url.Action("ListarVouchers", "Voucher", new { pagina = page }),
         new PagedListRenderOptions
         {
             DisplayLinkToLastPage = PagedListDisplayMode.IfNeeded,
             DisplayLinkToPreviousPage = PagedListDisplayMode.IfNeeded,
             Display = PagedListDisplayMode.IfNeeded,
             LinkToNextPageFormat = "Próximo",
             LinkToPreviousPageFormat = "Anterior"
         })
            </div>
        </div>
    </div>
}
else
{
    <p>Nenhum dado encontrato.</p>
}

PollPlus/Views/Voucher/NovoVoucher.cshtml
@model PollPlus.Models.VoucherViewModel

@{
    ViewBag.Title = "Novo Vocher";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="header">
    <h3>Cadastro de Voucher</h3>
</div>

<div class="content tamanho-reduzido">

    @if (ViewBag.Mesagem != null)
    {
        @*@Html.RenderPartial("~/Views/Shared/_PartialExibirColecaoDeErros.cshtml", (List<string>)ViewBag.Mesagem);*@
    }

    @using (Html.BeginForm("NovoVoucher", "Voucher", FormMethod.Post, new { role = "form", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        <div class="form-group">
            @Html.LabelFor(x => x.Descricao, "Descrição", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Descricao, new { @class = "form-control app" })
                @Html.ValidationMessageFor(x => x.Descricao)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Imagem", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                <input type="file" name="file" />
                <span style="font-size:9px;font-weight:bold">Tamanho permitido é 600 x 600 pixels</span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.DataValidade, "Valido Até:", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.DataValidade, new { @class = "form-control datepicker" })
                @Html.ValidationMessageFor(x => x.DataValidade)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Enquete", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.Partial("_DropDownListForEnquete")
                @Html.ValidationMessageFor(x => x.EnqueteId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.QtdeVoucherParaEmitir, "Quantidade de vouchers", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.QtdeVoucherParaEmitir, new { @class = "form-control app" })
                @Html.ValidationMessageFor(x => x.QtdeVoucherParaEmitir)
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <a class="btn btn-primary" onclick="javascript: GerarVouchers();">Gerar</a>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-primary" type="submit">Salvar</button>
            </div>
        </div>

        <div id="ListaDeVouchers" style="display:none">
            <input type="hidden" name="NroVoucher" id="NroVoucher" />
        </div>
    }

</div>

<script src="~/Scripts/jquery-2.1.3.min.js"></script>
@section Scripts{
    <script>
        function GerarVouchers() {

            var qtdeVoucher = $('#QtdeVoucherParaEmitir').val();

            if (qtdeVoucher != '') {

                var vouchers = '';

                for (var i = 0; i < qtdeVoucher; i++) {
                    vouchers += guid() + ',';
                }

                $('#NroVoucher').val(vouchers);

                alert('Vouchers gerados com sucesso, agora salve seu trabalho!');
            }
        }

        function guid() {
            function _p8(s) {
                var p = (Math.random().toString(16) + "000000000").substr(2, 8);
                return s ? "-" + p.substr(0, 4) + "-" + p.substr(4, 4) : p;
            }
            return _p8() + _p8(true) + _p8(true) + _p8();
        }

    </script>
}